name: Docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}

      - name: Generate docs
        run: |
          yarn install
          yarn docs

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          SINGLE_COMMIT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: docs
